### ISSUE TITLE
[Feat] 시간 뷰 구현

### ISSUE THREAD

**Issue by seojoozero** [Team-ZeroSugar/TIG-iOS#3]
## Issue

> 시간 뷰 구현

## Tasks

- [ ] 시간 설정 전 화면
- [ ] 가용 시간 화면
- [ ] 비가용 시간 화면
