### ISSUE TITLE
[Fix] 시간 탭 화면에서 활용 가능 시간 데이터가 제대로 표시되지 않는 문제를 수정합니다.

### ISSUE THREAD

**Issue by ljdongz** [Team-ZeroSugar/TIG-iOS#59]
## Issue

시간 탭 화면에서 활용 가능 시간 데이터가 제대로 표시되지 않는 문제를 수정합니다.

## Tasks

- 취침 시간이 다음날로 넘어갈 때 발생하는 문제
    - [x] 프로그래스 바가 채워지지 않는 문제
    - [x] 남은 활용 가능 시간이 0시간 0분으로 표시되는 문제
    - [x] 타임라인 정보가 표시되지 않는 문제
<img width="200" alt="1" src="https://github.com/user-attachments/assets/52bf90bf-df42-4374-abc0-035ff678af1e">

- 현재 시간이 수면 시간대에 위치해 있을 때 발생하는 문제
    - [x] 프로그래스 바가 채워지지 않는 문제
    - [x] 남은 활용 가능 시간이 0시간 0분으로 표시되는 문제
    - [ ] 타임라인 정보에 수면시간이라는 문구 표시
<img width="250" alt="1" src="https://github.com/user-attachments/assets/00a6323b-a81c-4e5b-afae-c3e122313f5c">
