### ISSUE TITLE
[Feature] 온보딩 & 홈 뷰 UI 수정

### ISSUE THREAD

**Issue by seojoozero** [Team-ZeroSugar/TIG-iOS#67]
## Issue

온보딩 뷰와 홈 뷰의 UI 수정 사항을 적용합니다.

## Tasks

- [x] 온보딩 시간 설정 뷰의 텍스트 색과 행간 수정
- [x] TimeView의 시간 표현 방식 수정
- [x] TimeView의 원형 타이머 색상과 모양 변경
